<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="16219" started-at="2021-01-22T06:42:20Z" finished-at="2021-01-22T06:42:36Z">
    <groups>
    </groups>
    <test name="Selenium" duration-ms="16219" started-at="2021-01-22T06:42:20Z" finished-at="2021-01-22T06:42:36Z">
      <class name="Testcases.RailWay.railways.TC14_BookTicket">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Testcases.RailWay.bookticket.BookTicketCommonTest@17c68925]" name="beforeClass" is-config="true" duration-ms="9446" started-at="2021-01-22T06:42:20Z" finished-at="2021-01-22T06:42:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TC14()[pri:0, instance:Testcases.RailWay.bookticket.BookTicketCommonTest@17c68925]" name="TC14" duration-ms="5375" started-at="2021-01-22T06:42:29Z" finished-at="2021-01-22T06:42:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Testcases.RailWay.railways.TC14_BookTicket.TC14(BookTicketCommonTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC14 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Testcases.RailWay.bookticket.BookTicketCommonTest@17c68925]" name="afterClass" is-config="true" duration-ms="1363" started-at="2021-01-22T06:42:34Z" finished-at="2021-01-22T06:42:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Testcases.RailWay.bookticket.BookTicketCommonTest -->
    </test> <!-- Selenium -->
  </suite> <!-- Default Suite -->
</testng-results>
